
S_FLD_HAZ_AR = {"DFIRM_ID": {'field_name': 'DFIRM_ID', 'field_type': 'Text', 'Required': 'R', 'field_length': 6, 'Domains': '', 'Related': ''},
"VERSION_ID": {'field_name': 'VERSION_ID', 'field_type': 'Text', 'Required': 'R', 'field_length': 11, 'Domains': '', 'Related': ''},
"FLD_AR_ID": {'field_name': 'FLD_AR_ID', 'field_type': 'Text', 'Required': 'R', 'field_length': 25, 'Domains': '', 'Related': ''},
"STUDY_TYP": {'field_name': 'STUDY_TYP', 'field_type': 'Text', 'Required': 'R', 'field_length': 38, 'Domains': 'D_Study_Typ'},
"FLD_ZONE": {'field_name': 'FLD_ZONE', 'field_type': 'Text', 'Required': 'R', 'field_length': 17, 'Domains': 'D_Zone'},
"ZONE_SUBTY": {'field_name': 'ZONE_SUBTY', 'field_type': 'Text', 'Required': 'A', 'field_length': 76, 'Domains': 'D_Zone_Subtype'},
"SFHA_TF": {'field_name': 'SFHA_TF', 'field_type': 'Text', 'Required': 'R', 'field_length': 1, 'Domains': 'D_TrueFalse'},
"STATIC_BFE": {'field_name': 'STATIC_BFE', 'field_type': 'Double', 'Required': 'A', 'field_length': ''},
"V_DATUM": {'field_name': 'V_DATUM', 'field_type': 'Text', 'Required': 'A', 'field_length': 17, 'Domains': 'D_V_Datum'},
"DEPTH": {'field_name': 'DEPTH', 'field_type': 'Double', 'Required': 'A', 'field_length': ''},
"LEN_UNIT":  {'field_name': 'LEN_UNIT', 'field_type': 'Text', 'Required': 'A', 'field_length': 16, 'Domains': 'D_Length_Units'},
"VELOCITY": {'field_name': 'VELOCITY', 'field_type': 'Double', 'Required': 'A', 'field_length': ''},
"VEL_UNIT": {'field_name': 'VEL_UNIT', 'field_type': 'Text', 'Required': 'A', 'field_length': 20, 'Domains': 'D_Velocity_Units'},
"AR_REVERT":  {'field_name': 'AR_REVERT', 'field_type': 'Text', 'Required': 'A', 'field_length': 17, 'Domains': 'D_Zone'},
"AR_SUBTRV": {'field_name': 'AR_SUBTRV', 'field_type': 'Text', 'Required': 'A', 'field_length': 76, 'Domains': 'D_Zone_Subtype'},
"BFE_REVERT": {'field_name': 'BFE_REVERT', 'field_type': 'Double', 'Required': 'A', 'field_length': ''},
"DEP_REVERT": {'field_name': 'DEP_REVERT', 'field_type': 'Double', 'Required': 'A', 'field_length': ''},
"DUAL_ZONE": {'field_name': 'DUAL_ZONE', 'field_type': 'Text', 'Required': 'A', 'field_length': 1, 'Domains': 'D_TrueFalse'},
"SOURCE_CIT": {'field_name': 'SOURCE_CIT', 'field_type': 'Text', 'Required': 'R', 'field_length': 11, 'Related': 'L_Source_Cit'}}

S_BFE = {
    "DFIRM_ID": {'field_name': 'DFIRM_ID', 'field_type': 'Text', 'Required': 'R', 'field_length': 6, 'Domains': '',
                 'Related': ''},
    "VERSION_ID": {'field_name': 'VERSION_ID', 'field_type': 'Text', 'Required': 'R', 'field_length': 11, 'Domains': '',
                   'Related': ''},
    "BFE_LN_ID": {'field_name': 'BFE_LN_ID', 'field_type': 'Text', 'Required': 'R', 'field_length': 25, 'Domains': '',
                  'Related': ''},
    "ELEV": {'field_name': 'ELEV', 'field_type': 'Double', 'Required': 'R', 'field_length': '', 'Domains': '',
             'Related': ''},
    "LEN_UNIT": {'field_name': 'LEN_UNIT', 'field_type': 'Text', 'Required': 'R', 'field_length': 16,
                 'Domains': 'D_Length_Units', 'Related': ''},
    "V_DATUM": {'field_name': 'V_DATUM', 'field_type': 'Text', 'Required': 'R', 'field_length': 17,
                'Domains': 'D_V_Datum', 'Related': ''},
    "SOURCE_CIT": {'field_name': 'SOURCE_CIT', 'field_type': 'Text', 'Required': 'R', 'field_length': 11, 'Domains': '',
                   'Related': 'L_Source_Cit'}
}